---
name: ci
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Setup enviroment
        run: pip install -r requirements-dev.txt
      - name: Run tests + cov report
        run: make test-with-coverage
      - name: Check style
        run: make checkstyle
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.xml
